import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import MainContainer from "@/components/Containers/MainContainer";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { dark } from "@clerk/themes";

const figtree = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        variables: {
          colorBackground: "#030712"
        }
      }}
    >
      <html lang="en">
        <body className={figtree.className}>
          <MainContainer>
            <Header />
            {children}
            <Footer />
          </MainContainer>
        </body>
      </html>
    </ClerkProvider>
  );
}
